FROM jenkins/jenkins:lts-jdk21

USER root

# Install Allure Commandline
RUN apt-get update && \
    apt-get install -y wget unzip && \
    wget -q https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip && \
    unzip -q allure-2.27.0.zip -d /opt && \
    ln -s /opt/allure-2.27.0/bin/allure /usr/bin/allure && \
    rm allure-2.27.0.zip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Verify Allure installation
RUN allure --version

USER jenkins

